title: Vishnu Venkatesh
email: vishnu.venkatesh1296@gmail.com
description: Personal website for Vishnu Venkatesh
baseurl: ""
url: "https://vishnu96.github.io"
github_username: Vishnu96

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed